Feature/ong4 33/formulario edicion creacion de usuarios
alkemyTech/React-SXXI-T4 pull request #1
Opened 2022-10-28 16:19 UTC by SoraBeat

En esta rama se realizo el ticket ONG4-33 el cual es realizar un formulario con los siguientes atributos y estilos:
-Nombre
-Email
-Contraseña
-Rol
-Foto de perfil
![image](https://user-images.githubusercontent.com/30334118/198684395-08836067-dd59-4972-9188-1f1cbf59fb3e.png)

La funcionalidad se basa en:
-Recibe un objeto usuario
-Llena los campos con los datos recibidos(si no ricibio nada aparecen vacios)
-Si llego un usuario lo modifica, sino lo crea.

Los campos del form estan componetizados, esto con el fin de reutilizarlos mas adenlantes en otros formularios de manera mas sencilla.

Los estilos estan aplicados con tailwind.

2022-10-28 21:37 UTC, SoraBeat commented
UPDATE: cambios menores en la estetica del formulario(placeholder, icono del boton password, nombre de la imagen seleccionada)
![image](https://user-images.githubusercontent.com/30334118/198737155-c4d1aa16-64c5-40a6-b195-5eb6784f4bdb.png)

2022-11-02 00:21 UTC, milandre commented on src/App.js
> +					{/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Si no se va a usar esta ruta por ahora, es mejor borrarla

2022-11-02 01:35 UTC, SoraBeat commented on src/App.js
> +					{/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Perfecto! ahi la quite

2022-11-02 02:03 UTC, milandre requested changes
@SoraBeat dejé comentarios y unos cambios para hacer con respecto a la parte de definir la creación y edición

2022-11-02 02:03 UTC, milandre commented on src/App.js
> +					<Route path="/create-user" element={<UserForm />} />
La historia de usuario (https://alkemy-labs.atlassian.net/browse/ONG4-33) dice que el componente debe ser reutilizable y que ese componente se debe usar en las rutas de edición y creación. Acá estoy viendo sólo la ruta de creación (/create-user), faltaría la ruta de edición o en su defecto hacer el manejo en una misma ruta para creación/edición. 

Ejemplo: 
    /backoffice/user ---> crear usuario
    /backoffice/user/:id ---> editar usuario

2022-11-02 02:03 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +import FormTitle from "../../common/Form/FormTitle";
Sugerencia:
Para las importaciones de este estilo que se hacen largas (../../../../), es mejor configurar rutas absolutas. Se puede hacer mediante un jsconfig.json que se crea en el directorio base de tu proyecto (al nivel del package.json) y hay una opción donde puedes elegir tu directorio base y hacer las importaciones a partir de ahi.

Ejemplo:

jsconfig.json
`{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}`

Quieres importar en un archivo un componente que está en src/components/Button.js, puedes hacerlo asi:
`import Button from 'components/Button';`

Más información en: https://create-react-app.dev/docs/importing-a-component/#absolute-imports

2022-11-02 02:03 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +		profile_image: yup.string().required("Imagen obligatoria"),
Falta la validación de que sea solo .jpg y .png

2022-11-02 02:03 UTC, milandre commented on src/Components/common/Form/InputImage.jsx
> +				setFieldValue(formikFieldName, url);
Acá está seteando cualquier archivo. Falta la validación de esta parte e informar al usuario que está intentando subir un archivo no permitido y que solo puede subir .png, .jpg.

Acá un ejemplo que te puede ayudar con esta parte. Hay una función validFileType que hacen en el ejemplo del cual t puedes basar: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#examples

2022-11-02 02:03 UTC, milandre commented on src/Components/common/Form/InputImage.jsx
> +					className={`flex flex-col items-center justify-center w-32 h-32 border-2 rounded-full border-gray-300 border-dashed hover:border-solid  cursor-pointer bg-gray-50  hover:bg-gray-100 bg-cover`}
No veo que se esté usando alguna variable dentro de los {``}, asi que las clases deberian estar dentro de comillas " "

2022-11-02 02:03 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +		if (user?.id) {
Esta validación debería ser a partir del id que viene de la ruta (referirse a useParams de react router dom para obtener parametros de una ruta), ya que si es la parte de creación, no vas a tener un id en el objeto (el id se crea en el backend).

2022-11-02 02:03 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +			<FormTitle>Crear/Editar Usuario</FormTitle>
Esto debería mostrar un Editar Usuario cuando estas en la vista de edición y un Crear Usuario cuando estás en la vista de creación

2022-11-02 02:03 UTC, milandre commented on src/Components/common/Form/FormInputPassword.jsx
> +			<button type="button" onClick={handleShowPassword}>
Buena idea de colocar un botón para visualizar u ocultar la contraseña. Faltaria cambiar a un ojo tachado o disabled cuando no quieras mostrarla.

2022-11-02 02:03 UTC, milandre commented on src/Components/common/Form/Form.jsx
> +			className="  flex flex-col justify-center align-middle w-11/12 md:w-3/4 lg:w-2/4 h-screen gap-3 mx-auto"
espacios innecesarios al principio del string de className

2022-11-03 16:19 UTC, milandre requested changes
@SoraBeat acá otras correcciones. Falta arreglar errores con respecto a la validación de la imagen y la parte en el useEffect con respecto a obtener los datos del usuario

2022-11-03 16:19 UTC, milandre commented on src/App.js
> +          <Route path="/backoffice/user" element={<UserForm />} />
arreglar identación

2022-11-03 16:19 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +	const SUPPORTED_FORMATS = [
mover esta const luego de las import y antes del UserForm

2022-11-03 16:19 UTC, milandre commented on src/Components/common/Form/InputImage.jsx
> +	const fileTypes = [
mover esta const despues de los import y antes de InputImage

2022-11-03 16:19 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +		axios
Sale error en consola cuando no se tiene un id. Falta validación acá
![image](https://user-images.githubusercontent.com/5572252/199769467-408dee35-2e73-42be-adf8-97011570c024.png)

2022-11-03 16:19 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +			value => value && SUPPORTED_FORMATS.includes(value.type)
Verificar estas validaciones porque subí un .png y me sale Formato no soportado
![image](https://user-images.githubusercontent.com/5572252/199771265-e43e7a7f-32dd-4b4f-94a6-73c3d2e81909.png)

2022-11-03 16:19 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +		profile_image: yup.string().required("Imagen obligatoria").test(
Si dejo sin subir una foto, me sale esto:
![image](https://user-images.githubusercontent.com/5572252/199772042-8699c96a-f0cd-4fa8-8c8f-5f81106dba39.png)

2022-11-03 16:54 UTC, SoraBeat commented
Cambios realizados, el problema de identacion es probable que venga de la configuracion de slint ya que al abrir el archivo todo se veia normal.

2022-11-03 17:00 UTC, milandre requested changes

2022-11-03 17:00 UTC, milandre commented on src/Components/Users/components/UsersForm.jsx
> +			.string("Hola")
¿Hay una forma de no hacer esto hardcodeado? ¿O colocando string vacío?

2022-11-03 17:02 UTC, SoraBeat commented on src/Components/Users/components/UsersForm.jsx
> +			.string("Hola")
Perdon ahi lo cambie era una prueba que hice y no borre ajsdjasd

2022-11-07 16:53 UTC, milandre approved these changes
@SoraBeat aprobado. Hay errores en el endpoint del PUT de usuarios, asi que te mantendré al tanto sobre esto a ver que se hace con el tema del email que no pueds dejar igual cuando quieres actualizar. Puedes mergear cuando quieras

2022-11-08 02:19 UTC, DiegoSantelices10 approved these changes

2022-11-10 14:31 UTC, merged