Screen con los datos de la ONG "Somos más"
alkemyTech/React-SXXI-T4 pull request #10
Opened 2022-11-01 23:55 UTC by gabrielpindo

![image](https://user-images.githubusercontent.com/69809704/199363462-1d87c36d-fc90-4ca0-8241-ac0f17d9feca.png)
![image](https://user-images.githubusercontent.com/69809704/199363487-eda26ef3-1cf3-4df0-9e5c-229cd8a545cd.png)

Con el link al cual le vamos a anexar la ruta hacia la edición del formulario. 
![image](https://user-images.githubusercontent.com/69809704/199363514-3e8223ae-9e5b-4b08-9b3b-7f909a71d0af.png)

2022-11-03 17:29 UTC, SoraBeat commented
Hay que borrar este comentario xd
![image](https://user-images.githubusercontent.com/30334118/199792054-2e956a4a-75e9-416b-8ad2-1a4e55ce6db9.png)
Esta etiqueta debe ser normal sin las llaves y debe llevar un alt(no es obligatorio pero dicen que es buena practica xd)
![image](https://user-images.githubusercontent.com/30334118/199792440-fa5127b8-f558-4f0f-957d-6043a2532e02.png)
Aqui se debe usar el componente Link de react router dom
![image](https://user-images.githubusercontent.com/30334118/199792647-841d96ea-f79a-4d59-a5e2-e5bc4d2b3474.png)

2022-11-08 17:49 UTC, milandre requested changes

2022-11-08 17:49 UTC, milandre commented on src/Components/DataONG/Data.jsx
> +        <div className="dataOrganization">
Los datos que acá se muestran, deben provenir del elemento de Organización con sus valores de name, image, shortDescription. Esta es la parte que iría vinculada en la vista del dashboard cuando le das click al botón de **Ir** en elemento de Organización que tienen acá en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/2 y en la rama feature/ONG4-51/ComponenteScreenDashboard(Backoffice). Diría que hables con @SoraBeat para que hagan primero el merge a dev de ese PR que ya está aprobado y luego actualices tu rama dev en local para luego actualizar esta y hacer la conexión entre el dashboard y esta parte. 

Pueden pasar la información como props desde el dashboard o hacer como que obtienen esos datos de la api acá mismo en el componente.

2022-11-12 03:04 UTC, gabrielpindo commented on src/Components/DataONG/Data.jsx
> +        <div className="dataOrganization">
Se resolvió, los datos mostrados son los de la api.

2022-11-14 01:34 UTC, milandre approved these changes

2022-11-25 17:41 UTC, merged