Feature/ong4 27/formulario creacion edicion de novedades
alkemyTech/React-SXXI-T4 pull request #11
Opened 2022-11-02 15:03 UTC by YonaBordon

Formulario Creacion / Edicion de Novedades

Criterios de aceptacion: 
- Contener campos titulo, contenido, cateogoria y imagen. 
- Formulario reutilizable para creacion y edicion
- Validaciones

Creacion
![image](https://user-images.githubusercontent.com/68975079/199523981-ac10d3fc-a25c-4887-852f-1ffb8342335d.png)

Edicion enviando id por parametro
![image](https://user-images.githubusercontent.com/68975079/199524130-a54bf51b-8dbd-443c-9c54-079bb9ff6ee7.png)

Validacion de campos
![image](https://user-images.githubusercontent.com/68975079/199524277-d617a759-7b2c-463c-a55e-99c569d6d9db.png)

2022-11-03 16:19 UTC, SoraBeat commented
Falta validacion de imagen, me deja seleccionar un video
![image](https://user-images.githubusercontent.com/30334118/199775749-00008f99-1e52-4f1c-8811-b8b4f4c14159.png)

2022-11-03 17:32 UTC, SoraBeat commented
Falta borrar este comentario, por lo demas creo que esta todo joya 👌😁
![image](https://user-images.githubusercontent.com/30334118/199793424-08e4ab21-ff70-4099-a4ec-87744348db7b.png)

2022-11-08 18:32 UTC, milandre requested changes

2022-11-08 18:32 UTC, milandre commented on src/App.js
> +					<Route path="/create-news" element={<NewsForm />} />
La ruta debe ser `backoffice/news`

2022-11-08 18:32 UTC, milandre commented on src/App.js
> +					<Route path="/create-news/:id" element={<NewsForm />} />
La ruta debe ser `backoffice/news/:id`

2022-11-08 18:32 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +import "../../Components/FormStyles.css";
Hay que cambiar esta ruta a ruta absoluta cuando este actualizado dev con el PR #1 donde se encuentra el `jsonconfig.json` 

Mas información de lo que son rutas absolutas en el mensaje de acá: https://github.com/alkemyTech/React-SXXI-T4/pull/1#discussion_r1011041670

2022-11-08 18:32 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +						<form className="form-container" onSubmit={handleSubmit}>
Los estilos y estructura de este formulario deben ser consistentes con los otros formularios que han sido creados para la parte del administrador. Sugiero reunirse con @SoraBeat para ponerse de acuerdo con esto.

2022-11-08 18:32 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +				<h2> Cargando...</h2>
Revisar estilo de la parte del Cargando para mantenerlo consistente en el proyecto. Hablar con el equipo.

2022-11-08 18:32 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +			Swal.fire(
Revisar estilos de las alertas también para mantenerlos consistentes. Hablar con tu equipo.

2022-11-16 22:06 UTC, milandre requested changes

2022-11-16 22:06 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +					console.log(values);
Borrar console.log

2022-11-16 22:06 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +		console.log(values);
Borrar console.log

2022-11-16 22:06 UTC, milandre commented on src/Components/News/NewsForm.jsx
> +		console.log(categories);
Borrar console.log

2022-11-16 22:06 UTC, milandre commented on src/Components/News/NewsForm.jsx
>  					values
Acá no deja actualizar si envias el campo de image como un link. Si no se modificó la imagen, no se tiene que pasar el campo de image en values. Si se modificó la imagen, ahi si tienes que pasarla en un string base64

2022-11-16 22:28 UTC, YonaBordon commented on src/Components/News/NewsForm.jsx
>  					values
Ahi lo arreglé, gracias andre

2022-11-16 22:45 UTC, milandre approved these changes

2022-11-17 00:30 UTC, merged