Tarea Completada
alkemyTech/React-SXXI-T4 pull request #12
Opened 2022-11-02 17:52 UTC by DiegoSantelices10

se realizó el formulario de creación y edición de categorías, reutilizando un solo formulario para las dos opciones.

![Screenshot_5](https://user-images.githubusercontent.com/70447941/199564553-a1ce00c7-476e-471b-903e-8db43d10b24b.png)
![Screenshot_6](https://user-images.githubusercontent.com/70447941/199564594-03f550c7-9d12-4af4-a321-be9acac47ed1.png)

2022-11-03 17:39 UTC, SoraBeat commented
Falta borrar este comentario xd
![image](https://user-images.githubusercontent.com/30334118/199793725-f9f43cf5-9740-44a9-9bcd-1c9b76e59fc2.png)
Cambiar el mensaje de error al submitear y no haber seleccionado una imagen
![image](https://user-images.githubusercontent.com/30334118/199794171-4d2c9cca-9445-4704-95fe-8e223a645388.png)
Al insertar un video no me salta error de tipo de archivo (png jpg)
![image](https://user-images.githubusercontent.com/30334118/199794638-d0023669-d8b4-481b-9542-877c003488c3.png)

2022-11-08 21:05 UTC, milandre requested changes

2022-11-08 21:05 UTC, milandre commented on src/Components/Categories/CategoriesForm.js
> +							name: yup.string().required(message),
Falta validación de longitud minima de 4 carateres

2022-11-08 21:05 UTC, milandre commented on src/Components/Categories/CategoriesForm.js
> +		<div className="h-screen">
Los estilos y estructura de este formulario deben ser consistentes con los otros formularios que han sido creados para la parte del administrador. Sugiero reunirse con @SoraBeat, @YonaBordon, @gabrielpindo y ponerse de acuerdo con esto.

2022-11-09 04:35 UTC, DiegoSantelices10 commented on src/Components/Categories/CategoriesForm.js
> +		<div className="h-screen">
Dale Andre queda pendiente esta corrección para cuando definamos una estructura con mis compañeros.

2022-11-15 00:24 UTC, DiegoSantelices10 commented
Andre ahi resolvimos el diseño del formulario para todo el backoffice ya realice los cambio en esta rama

2022-11-15 00:25 UTC, DiegoSantelices10 commented
![Screenshot_15](https://user-images.githubusercontent.com/70447941/201796045-4f3a2812-5672-4b92-83ca-5d3682318313.png)

2022-11-16 22:20 UTC, milandre approved these changes

2022-11-17 06:11 UTC, merged