Creación del formulario de creación/edición de testimonios
alkemyTech/React-SXXI-T4 pull request #13
Opened 2022-11-03 13:56 UTC by gabrielpindo

![image](https://user-images.githubusercontent.com/69809704/199739679-d3e2d1c9-30a7-40c8-bf4d-cdc9d02c9372.png)
![image](https://user-images.githubusercontent.com/69809704/199739765-be9efa29-1ed0-4a46-a33e-b0bf5886a0f2.png)

2022-11-03 18:09 UTC, SoraBeat commented
Falta borrar este comentario xd
![image](https://user-images.githubusercontent.com/30334118/199801044-cd840806-52fb-490f-a520-a7b829b849b9.png)
Falta validacion de imagen al ingresar un formato que no es png/jpg (me deja seleccionar un video y no salta error al submitear)
![image](https://user-images.githubusercontent.com/30334118/199800927-c9a833c7-da36-492d-8828-82bafecd2e03.png)
![image](https://user-images.githubusercontent.com/30334118/199801165-1a5b1f85-a839-4ed8-9333-b439ea080e24.png)

2022-11-08 20:36 UTC, milandre requested changes
@gabrielpindo TestimonialsForm.css es un archivo vacio que no deberia estar. Eliminarlo o en su defecto, colocar los estilos relacionados en ese archivo

2022-11-08 20:36 UTC, milandre commented on public/style.css
> +
Eliminar espacios extra

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +				.catch(error => console.log(error));
Añadir sweetalert2 aca para los mensajes de error que sean consistentes con los otros formularios de la parte del backoffice

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +								.then(res => console.log(res))
Añadir sweetalert2 aca para los mensajes de error que sean consistentes con los otros formularios de la parte del backoffice

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +								.catch(err => console.log(err));
Añadir sweetalert2 aca para los mensajes de error que sean consistentes con los otros formularios de la parte del backoffice

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +								.then(res => console.log(res))
Añadir sweetalert2 aca para los mensajes de error que sean consistentes con los otros formularios de la parte del backoffice

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +								.catch(err => console.log(err));
Añadir sweetalert2 aca para los mensajes de error que sean consistentes con los otros formularios de la parte del backoffice

2022-11-08 20:36 UTC, milandre commented on src/App.js
> +          <Route path="/create-testimonials/:id" element={<TestimonialForm/>} />
Como esto pertenece al backoffice, deberia tener una ruta con /backoffice/. Cambiar a `/backoffice/testimonials/:id
`

2022-11-08 20:36 UTC, milandre commented on src/App.js
>            <Route path="/create-testimonials" element={<TestimonialForm/>} />
Como esto pertenece al backoffice, deberia tener una ruta con /backoffice/. Cambiar a `/backoffice/testimonials`

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +			<div className="w-full sm:w-full sm:mx-auto md:w-1/2 lg:w-4/5 md:mx-auto flex flex-col justify-center items-center">
Los estilos y estructura de este formulario deben ser consistentes con los otros formularios que han sido creados para la parte del administrador. Sugiero reunirse con @SoraBeat, @YonaBordon, @DiegoSantelices10 para ponerse de acuerdo con esto.

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +									placeholder="Ingresa el nombre de la categoria"
Deberia decir "Ingresa el nombre del testimonio"

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +										{!id ? "Subir testimonio" : "Actualizar testimonio"}
Cambiar "Subir testimonio" por "Crear testimonio"

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +							image: yup.string().required().oneOf(["image/png", "image/jpg"],messageImg)
Revisar validaciones de imagen. Me sale esto y no me deja crear:
![image](https://user-images.githubusercontent.com/5572252/200669221-1db16d78-e69b-4231-abc6-3a8ca8d6a6c4.png)

2022-11-08 20:36 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +						name: "",
¿Qué pasa si estoy en la vista de edición con los initialValues? Revisar esta parte. Trato de modificar solo la imagen para probar la actualización y me aparecen estos errores que no deberían estar
![image](https://user-images.githubusercontent.com/5572252/200669916-cf29c0ff-42f6-40ab-8789-a62a57203485.png)

2022-11-16 22:37 UTC, milandre requested changes

2022-11-16 22:37 UTC, milandre commented on src/Services/Testimonials/testimonials.js
> +			console.log(res);
Borrar console.log

2022-11-16 22:37 UTC, milandre commented on src/Services/Testimonials/testimonials.js
> +			console.log(res);
Borrar console.log

2022-11-16 22:37 UTC, milandre commented on src/Components/common/Form/Form.jsx
> +		<Form className=" lg:shadow rounded-md  w-full sm:w-4/5 md:w-11/12 lg:w-4/5  bg-white py-7">
Revisar el estilo en el PR #12 para que quede el formulario centrado

2022-11-16 22:37 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +								<FormError />
Acá falta las props correspondientes a la imagen (error y touched)

2022-11-18 03:13 UTC, gabrielpindo commented
Se realizaron los cambios necesarios.

2022-11-21 20:49 UTC, milandre requested changes

2022-11-21 20:49 UTC, milandre commented on src/Services/privateApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Aca deberia ser grupo 4

2022-11-21 20:49 UTC, milandre commented on src/Services/publicApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Aca deberia ser grupo 4

2022-11-21 20:49 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.js
> +		<div className="w-full flex justify-center">
Falta centrarlo a lo vertical

2022-11-21 20:49 UTC, milandre commented on public/style.css
> +
@gabrielpindo falta modificar aca

2022-11-21 20:49 UTC, milandre commented on src/App.js
>            <Route path="/create-testimonials" element={<TestimonialForm/>} />
@gabrielpindo falta hacer esto

2022-11-21 20:49 UTC, milandre commented on src/App.js
> +          <Route path="/create-testimonials/:id" element={<TestimonialForm/>} />
@gabrielpindo falta hacer esto

2022-11-21 23:56 UTC, milandre approved these changes

2022-11-25 18:00 UTC, merged