Feature/ONG4-34/formulario de edición de organización
alkemyTech/React-SXXI-T4 pull request #14
Opened 2022-11-03 20:30 UTC by DiegoSantelices10

Se realizó el formulario de edición de organización, con sus respectivas consignas, lo único que me quedo validar en principio es el tema de imágenes Andre como mencionaste en las otras tareas. Para la noche lo resuelvo

2022-11-04 04:57 UTC, DiegoSantelices10 commented
![Screenshot_10](https://user-images.githubusercontent.com/70447941/199891069-dbb9b1af-2c06-45f8-b7bd-e60105183fa1.png)
![Screenshot_9](https://user-images.githubusercontent.com/70447941/199891075-f91ea888-94c7-4db2-bc59-0259b679a6f8.png)
![Screenshot_8](https://user-images.githubusercontent.com/70447941/199891088-35447bf6-09ed-4ace-b526-21efa1f36c63.png)

2022-11-08 21:11 UTC, milandre requested changes

2022-11-08 21:11 UTC, milandre commented on src/Components/Organization/OrganizationForm.js
> +			<div
Los estilos y estructura de este formulario deben ser consistentes con los otros formularios que han sido creados para la parte del administrador. Sugiero reunirse con @SoraBeat, @YonaBordon, @gabrielpindo  para ponerse de acuerdo con esto.

2022-11-08 21:11 UTC, milandre commented on src/Components/Organization/OrganizationForm.js
> +} from "../../Services/Organization/ApiService";
Hay que cambiar esta ruta a ruta absoluta cuando este actualizado dev con el PR https://github.com/alkemyTech/React-SXXI-T4/pull/1 donde se encuentra el jsonconfig.json

Mas información de lo que son rutas absolutas en el mensaje de acá: https://github.com/alkemyTech/React-SXXI-T4/pull/1#discussion_r1011041670

2022-11-08 21:11 UTC, milandre commented on src/Services/Organization/ApiService.js
> +		.put(`https://ongapi.alkemy.org/api/organization/1`, values)
El numero 1 del id de la organización no debería estar hardcodeado. Puedes colocarlo como constante o como variable de entorno

2022-11-09 04:47 UTC, DiegoSantelices10 commented on src/Services/Organization/ApiService.js
> +		.put(`https://ongapi.alkemy.org/api/organization/1`, values)
Se realizaron los cambios!

2022-11-10 03:40 UTC, DiegoSantelices10 commented on src/Components/Organization/OrganizationForm.js
> +} from "../../Services/Organization/ApiService";
dale andre lo resuelvo cuando hago merge con dev!

2022-11-14 01:51 UTC, milandre approved these changes

2022-11-15 00:29 UTC, merged