Features/ong4 50/crear componente detalle actividades
alkemyTech/React-SXXI-T4 pull request #15
Opened 2022-11-04 00:21 UTC by JorgeGarciaMdz

Me falta darle formato a la descripcion y tamaño a la imagen
Utilizo el compoente Title que se pide en la rama o tarjeta 48 que aun no esta en dev

2022-11-16 23:04 UTC, milandre requested changes

2022-11-16 23:04 UTC, milandre commented on src/App.js
> +
Eliminar linea extra

2022-11-16 23:04 UTC, milandre commented on src/Components/Activities/ActivityDetails.js
> +import { Title } from "../Title/Title";
Acá debería ser
`import Title  from "../Title/Title";`

2022-11-16 23:04 UTC, milandre commented on src/App.js
> +          <Route path="/activity/:id" element={ <ActivityDetails /> } />
Quitar esta linea y dejar la que esta en linea 22

2022-11-16 23:13 UTC, milandre requested changes

2022-11-16 23:13 UTC, milandre commented on src/Components/Activities/ActivityDetails.js
> +						<div
Esta parte tienes que cambiarla por el componente de contenido de actividad que esta en PR #16. Sugiero hables con @SoraBeat para que se pongan de acuerdo en cual va a ser el estilo y cual dejarian si esta version o la otra

2022-11-17 17:41 UTC, SoraBeat commented on src/Components/Activities/ActivityDetails.js
> +						<div
Se charlo con @JorgeGarciaMdz y se eligio los estilos. Ya los commiteo

2022-11-17 18:59 UTC, milandre approved these changes
@JorgeGarciaMdz primero cambia las cosas que te deje de las importaciones y luego ya estaria para hacerle merge

2022-11-17 18:59 UTC, milandre commented on src/Components/Activities/ActivitiesList.js
> +import { findAll } from "../../Services/ActivitiesServices";
Cambiar ruta a `'Services/ActivitiesServices'`

2022-11-17 18:59 UTC, milandre commented on src/Components/Activities/index.js
> +export { findAll, findById } from '../../Services/ActivitiesServices';
Cambiar a `'Services/ActivitiesServices'`

2022-11-29 21:43 UTC, merged