Feature/ong4 58/crear componente contenido de actividad
alkemyTech/React-SXXI-T4 pull request #16
Opened 2022-11-05 17:30 UTC by SoraBeat

En esta rama se realizo un componente el cual recibe por parametros un contenido html y lo renderiza. 
Aqui una prueba:
Declarando componente y pasandole un texto de prueba
![image](https://user-images.githubusercontent.com/30334118/200133267-acad1085-48e5-464c-8a4c-425e9c534bb4.png){
Resultado
![image](https://user-images.githubusercontent.com/30334118/200133305-83cf7a4e-cfae-44e0-a56d-daa494dc2dd6.png)

2022-11-16 23:13 UTC, milandre requested changes

2022-11-16 23:13 UTC, milandre commented on src/Components/Activities/ContentActivities.jsx
> +	return <div dangerouslySetInnerHTML={{ __html: content }} />;
En el PR #15 hay un estilo que se reemplazaria por este componente. Sugiero hablar con @JorgeGarciaMdz para ver con cual version se quedan

2022-11-17 17:42 UTC, SoraBeat commented on src/Components/Activities/ContentActivities.jsx
> +	return <div dangerouslySetInnerHTML={{ __html: content }} />;
Ya se hablo con @JorgeGarciaMdz y se realizaron los cambios en su rama llevandose el componente para poder utilizarlo.

2022-11-17 19:00 UTC, milandre approved these changes

2022-11-17 19:18 UTC, merged