Feature/ong4 57/crear componente para renderizar seccion actividades
alkemyTech/React-SXXI-T4 pull request #17
Opened 2022-11-05 17:51 UTC by SoraBeat

En esta rama se realizo el renderizado del componente ActivitiesList el cual se renderiza al ingresar a /actividades. El componente titulo es el realizado por Gabriel Pindo en la rama features/ONG4-48/ComponenteTitulo.
Ejemplo:
![image](https://user-images.githubusercontent.com/30334118/200134136-95071334-0bc2-475d-af77-1a624bd25625.png)

2022-11-07 16:08 UTC, JorgeGarciaMdz approved these changes
Se todo funcional.

2022-11-16 23:19 UTC, milandre requested changes

2022-11-16 23:19 UTC, milandre commented on src/Components/Activities/ActivitiesList.jsx
> +	const activitiesMock = [
Eliminar mock

2022-11-16 23:19 UTC, milandre commented on src/Components/Activities/ActivitiesList.jsx
> +				{activitiesMock.length > 0 ? (
En el PR #15  hay una version ya con la llamada al endpoint, la cual colocaria de una vez. Sugiero hables con @JorgeGarciaMdz para ver esto y ademas decidir cuales estilos van a dejar para esta seccion

2022-11-16 23:28 UTC, milandre commented
Hablar con @DiegoSantelices10 porque el tiene otro estilo para la lista de Novedades (PR #22) usando el componente Card y esta secci'on deberia quedar parecido en cuanto a las cards y mostrar la informaci'on.

2022-11-17 17:43 UTC, SoraBeat commented on src/Components/Activities/ActivitiesList.jsx
> +				{activitiesMock.length > 0 ? (
Ya se hablo con @JorgeGarciaMdz creando un archivo en Services para poder realizar las llamadas al endpoint. Falta implementarlo.

2022-11-17 19:52 UTC, SoraBeat commented on src/Components/Activities/ActivitiesList.jsx
> +	const activitiesMock = [
Corregido

2022-11-17 19:54 UTC, SoraBeat commented on src/Components/Activities/ActivitiesList.jsx
> +				{activitiesMock.length > 0 ? (
Corregido, se realizo el fetch de acuerdo a lo realizado por @JorgeGarciaMdz

2022-11-17 20:04 UTC, milandre requested changes

2022-11-17 20:04 UTC, milandre commented on src/Components/Activities/ActivitiesList.jsx
> +				<Title text="Novedades" />
El titulo acá deberia ser Actividades

2022-11-17 20:04 UTC, milandre commented on src/Components/Card/CardActivity.jsx
> +const CardActivity = ({ activity }) => {
Acá deberia ser el componente Card generico del PR #18. Sugiero hablar con @gabrielpindo y todos los demas a ver que van a hacer con lo del componente Card en cuanto a estlos y uso

2022-11-17 20:09 UTC, SoraBeat commented on src/Components/Activities/ActivitiesList.jsx
> +				<Title text="Novedades" />
Perdon se me paso asjdjasd Corregido 👌

2022-11-17 22:36 UTC, SoraBeat commented on src/Components/Card/CardActivity.jsx
> +const CardActivity = ({ activity }) => {
Hola Andree, nos juntamos para terminar de refinar el funcionamiento del componente Card. Ahi realice los cambios utilizando el componente Card realizado en el PR #18 .

2022-11-21 21:39 UTC, milandre approved these changes
@SoraBeat falta que hagas un cambio y de resto esta bien, lo apruebo

2022-11-21 21:39 UTC, milandre commented on src/Components/Activities/ActivitiesList.jsx
> +							description={activity.description}
Acá colocaría algo asi
`description={activity.description?.length > 80 ? ``${activity.description?.substring(0, 80)}...``: activity.description}`
para evitar que cuando haya mucho texto en la descripcion, se vea con el scroll.

2022-11-22 20:50 UTC, merged