Creación del componente <Card />
alkemyTech/React-SXXI-T4 pull request #18
Opened 2022-11-05 23:48 UTC by gabrielpindo

Se creó el componente card, que será utilizado para mostrar testimonios, al staff, las actividades, etc. 
![tarjetasVista3](https://user-images.githubusercontent.com/69809704/200147309-c35a9e4b-8e17-4123-982b-0f7904cdab6e.png)
![TarjetasVistaPropiedades](https://user-images.githubusercontent.com/69809704/200147312-b6af17f8-aa57-4034-a125-5c310e13d83b.png)

2022-11-07 16:00 UTC, JorgeGarciaMdz approved these changes
Se ve todo bien.

2022-11-09 23:58 UTC, milandre requested changes

2022-11-09 23:58 UTC, milandre commented on src/Components/Card/Card.jsx
> +                    <img src={`${data.image}`} alt="img no disponible" />
Cambiar el texto del alt para que maneje tanto si hay imagen o no

2022-11-09 23:58 UTC, milandre commented on src/Components/Card/Card.jsx
> +                    <div style={divStyle} className="cardMedia">
Consulta, ¿Qué haria este div? ¿Sólo colocar el backgroundColor?

2022-11-09 23:58 UTC, milandre commented on src/Components/Card/Card.jsx
> +                                <a href={`${data.facebook}`} target="_blank" rel='noreferrer'>
¿Qué pasa si las redes sociales están con string "" o null?

2022-11-10 13:44 UTC, gabrielpindo commented on src/Components/Card/Card.jsx
> +                                <a href={`${data.facebook}`} target="_blank" rel='noreferrer'>
Hay que colocar en el atributo "socialMedia=false", y muestra solo el campo vacío a color, sin los íconos de redes sociales.

2022-11-12 03:00 UTC, gabrielpindo commented on src/Components/Card/Card.jsx
> +                    <img src={`${data.image}`} alt="img no disponible" />
Ya se resolvió, muestra una imagen por defecto si no detecta una imagen en los atributos.

2022-11-12 03:01 UTC, gabrielpindo commented on src/Components/Card/Card.jsx
> +                    <div style={divStyle} className="cardMedia">
Si, solo eso a modo de detalle, si no recibe los atributos de "facebook" o "linkedin". Si los recibe, muestra otro contenedor con los iconos de las redes.

2022-11-12 03:02 UTC, gabrielpindo commented on src/Components/Card/Card.jsx
> +                                <a href={`${data.facebook}`} target="_blank" rel='noreferrer'>
Se resolvió, si recibe un parametro nulo, vacío ( " " ) o indefinido, no muestra los íconos de las redes sociales.

2022-11-14 02:06 UTC, milandre approved these changes

2022-11-16 01:13 UTC, SoraBeat approved these changes

2022-11-17 21:38 UTC, gabrielpindo commented
Buenas tardes, se realizó en el último commit pair programming para definir el comportamiento de la Card y los estilos.

2022-11-17 21:41 UTC, merged