Features/ong4 29/formulario edicion creacion actividades
alkemyTech/React-SXXI-T4 pull request #19
Opened 2022-11-07 01:02 UTC by JorgeGarciaMdz

formulario creacion edicion de actividades echo, se creo a nivel componente una clase servicio que realiza las peticiones al backend.

2022-11-08 21:46 UTC, milandre requested changes

2022-11-08 21:46 UTC, milandre commented on src/App.js
> +          <Route path="/create-activity/:id" element={<ActivitiesForm/>} />
La ruta deberia ser algo relacionado a edición. Ejemplo `backoffice/edit-activity/:id`

2022-11-08 21:46 UTC, milandre commented on src/Components/Activities/ActivitiesDetails.js
> +import { Title } from "../Title/Title";
Error de importación. Hay que actualizar la rama para traer el componente y lo puedas usar.

2022-11-08 21:46 UTC, milandre commented on src/Components/Activities/ActivitiesForm.js
> +		<div className="h-screen">
Los estilos y estructura de este formulario deben ser consistentes con los otros formularios que han sido creados para la parte del administrador. Sugiero reunirse con @SoraBeat, @YonaBordon, @gabrielpindo, @DiegoSantelices10  y ponerse de acuerdo con esto.

2022-11-08 21:46 UTC, milandre commented on src/App.js
>            <Route path="/create-activity" element={<ActivitiesForm/>} />
La ruta debe ser `backoffice/create-activity`

2022-11-09 00:28 UTC, JorgeGarciaMdz commented on src/Components/Activities/ActivitiesDetails.js
> +import { Title } from "../Title/Title";
El componente esta creado en alguna rama pero no ha sido mergeado a dev, por lo cual, al actualizar mi rama con dev no se encuentra el componente Title.

2022-11-16 23:22 UTC, milandre commented on src/Components/Activities/ActivitiesDetails.js
> +import { Title } from "../Title/Title";
Acá debería ser
import Title from "../Title/Title";

2022-11-16 23:54 UTC, JorgeGarciaMdz commented
utilizacion formulario concensuado

2022-11-17 11:51 UTC, milandre requested changes

2022-11-17 11:51 UTC, milandre commented on src/Components/Activities/ActivitiesForm.js
> +						description: yup.string().required(message),
Arreglar indentación

2022-11-17 11:51 UTC, milandre commented on src/Components/Activities/ActivitiesForm.js
> +						image: yup.string().required(message)
Arreglar indentación

2022-11-17 11:51 UTC, milandre commented on src/Components/Activities/ActivitiesForm.js
> +				console.log(resp)
Borrar console.log

2022-11-17 11:51 UTC, milandre commented on src/App.js
> +            <Route path="/backoffice/edit-activity/:id" element={<ActivitiesForm />} />
Arreglar indentación

2022-11-23 23:20 UTC, JorgeGarciaMdz commented on src/App.js
> +            <Route path="/backoffice/edit-activity/:id" element={<ActivitiesForm />} />
identacion corregida

2022-11-23 23:20 UTC, JorgeGarciaMdz commented on src/Components/Activities/ActivitiesForm.js
> +				console.log(resp)
borrado linea 46

2022-11-23 23:21 UTC, JorgeGarciaMdz commented on src/Components/Activities/ActivitiesForm.js
> +						image: yup.string().required(message)
corregido

2022-11-23 23:21 UTC, JorgeGarciaMdz commented on src/Components/Activities/ActivitiesForm.js
> +						description: yup.string().required(message),
corregido

2022-11-28 09:48 UTC, milandre approved these changes

2022-11-29 20:45 UTC, merged