Creacion de componente
alkemyTech/React-SXXI-T4 pull request #20
Opened 2022-11-07 04:32 UTC by DiegoSantelices10

Se creo el componente de contacto donde se muestra los datos de la ONG

![Screenshot_11](https://user-images.githubusercontent.com/70447941/200227038-0d6377ed-20d2-4049-8037-5f64f360a6dc.png)

2022-11-07 04:36 UTC, DiegoSantelices10 commented
Aclaración: Se realizó una condición para la muestra de los datos ya que aun no estamos obteniendo los datos de la API, mas que nada para que se muestre info en el front.

2022-11-14 02:10 UTC, milandre requested changes

2022-11-14 02:10 UTC, milandre commented on src/App.js
> +	const dataContact = {
Eliminar datos para testear. Dejar solo lo del componente.

2022-11-14 02:10 UTC, milandre commented on src/App.js
> +					<Route path="/contacto" element={<Contact data={dataContact} />} />
Eliminar datos para testear. Dejar solo lo del componente.

2022-11-15 00:34 UTC, DiegoSantelices10 commented
Listo Andre ahi elimine los datos de prueba!

2022-11-16 23:24 UTC, milandre approved these changes

2022-11-17 06:14 UTC, merged