Creación de componente de novedades
alkemyTech/React-SXXI-T4 pull request #22
Opened 2022-11-08 02:06 UTC by DiegoSantelices10

Se muestran los datos de forma dinámica de las ultimas novedades

![Screenshot_12](https://user-images.githubusercontent.com/70447941/200457249-45a61394-0a17-4541-8878-57dc34044e8a.png)

2022-11-14 02:26 UTC, milandre requested changes

2022-11-14 02:26 UTC, milandre commented on src/Components/Card/Card.js
> +export default function Card({ data }) {
¿El componente va a ser este o el que está en `features/ONG4-60/Card`? Ya el PR #18 está aprobado así que se tienen que poner de acuerdo cual va a ser el componente Card a usar y cambiarlo segun el decidido

2022-11-14 02:26 UTC, milandre commented on src/App.js
> +	const data = [
Eliminar datos de testing

2022-11-15 02:52 UTC, DiegoSantelices10 commented on src/Components/Card/Card.js
> +export default function Card({ data }) {
Se realiza un componente Card llamado CardNews porque maneja diferentes valor y elemento en el contenido.

2022-11-16 23:31 UTC, milandre commented on src/Components/Card/Card.js
> +export default function Card({ data }) {
@DiegoSantelices10 sugiero reunirse con @gabrielpindo para llegar a un acuerdo en esto porque la idea es que se use un solo componente Card para estas secciones

2022-11-23 03:46 UTC, DiegoSantelices10 commented on src/Components/Card/Card.js
> +export default function Card({ data }) {
Se realizaron los cambios!

2022-11-28 09:55 UTC, milandre approved these changes

2022-11-29 01:30 UTC, merged