Creación del componente <Staff />
alkemyTech/React-SXXI-T4 pull request #24
Opened 2022-11-08 04:38 UTC by gabrielpindo

Este componente lista los miembros de la ONG "Somos más".

![StaffGridCompleta](https://user-images.githubusercontent.com/69809704/200476158-d4ce576b-8213-4616-bd33-dc965ae8643d.png)
![StaffTablet](https://user-images.githubusercontent.com/69809704/200476163-7a953057-f465-49d5-b10a-46ef2c82b729.png)
![StaffMovil](https://user-images.githubusercontent.com/69809704/200476181-4c768f68-be7d-4afd-982f-22ec21f1c174.png)

2022-11-09 00:24 UTC, JorgeGarciaMdz approved these changes
esta todo bien.

2022-11-14 02:31 UTC, milandre requested changes

2022-11-14 02:31 UTC, milandre commented on src/Components/Card/Card.jsx
> +                {data.socialMedia === true ?
Se hicieron cambios en este componente que estan en el PR #18. Hacerle merge al PR #18 a dev y luego actualizar esta rama con los cambios

2022-11-14 02:31 UTC, milandre commented on src/Components/Staff/Staff.jsx
> +                        <Card
¿El componente va a ser este o el que está en features/ONG4-60/Card? Ya el PR #18  está aprobado así que se tienen que poner de acuerdo cual va a ser el componente Card a usar y cambiarlo segun el decidido

2022-11-16 23:34 UTC, milandre requested changes
Hablar con @DiegoSantelices10 para que lleguen a un acuerdo sobre el componente Card para las distintas secciones de la parte del usuario regular. La idea es que usen un solo componente para estas secciones

2022-11-25 18:02 UTC, gabrielpindo commented
Cambios realizados, se va a elegir el estilo de tarjeta que se estaba usando.

2022-11-28 09:54 UTC, milandre approved these changes

2022-11-29 23:45 UTC, merged