features/ONG4-54/CrearComponenteSeccionNosotros: show us information,…
alkemyTech/React-SXXI-T4 pull request #26
Opened 2022-11-09 11:36 UTC by JorgeGarciaMdz

… long and short description. Use Title component

2022-11-14 02:55 UTC, milandre requested changes

2022-11-14 02:55 UTC, milandre commented on src/Components/About/About.js
> +				console.log(resp.data.data);
Borrar console.log

2022-11-14 02:55 UTC, milandre commented on src/Components/About/About.js
> +        console.log(shortLongDescription);
Borrar console.log

2022-11-14 02:55 UTC, milandre commented on src/Components/About/About.js
> +import { Title } from "../Title/Title";
Revisar esta importación luego de que hagan merge a PR #9

2022-11-17 19:08 UTC, milandre commented on src/Components/About/About.js
> +import { Title } from "../Title/Title";
Cambiar a `import Title from "../Title/Title";`

2022-11-23 23:28 UTC, JorgeGarciaMdz commented on src/Components/About/About.js
> +				console.log(resp.data.data);
borrado

2022-11-23 23:28 UTC, JorgeGarciaMdz commented on src/Components/About/About.js
> +        console.log(shortLongDescription);
borrado

2022-11-23 23:31 UTC, JorgeGarciaMdz commented on src/Components/About/About.js
> +import { Title } from "../Title/Title";
Realizado

2022-11-28 09:56 UTC, milandre approved these changes

2022-11-30 00:48 UTC, merged