features/ONG4-59/ComponenteParaRenderizarSeccionesDonacionYGracias: s…
alkemyTech/React-SXXI-T4 pull request #28
Opened 2022-11-14 11:56 UTC by JorgeGarciaMdz

…e ha creado el componente donacion y gracias, se utiliza el COMPONENTE TITLE QUE AUN NO ESTA MERGEADO CON DEV

2022-11-16 01:03 UTC, SoraBeat commented
Buenas, te dejo un par de comentarios para que tengas en cuenta ^^
Ojo que cuando realizamos un componente funcional tenemos pactado crearlos con la extencion JSX
![image](https://user-images.githubusercontent.com/30334118/202057094-452956e5-68ce-4cba-81cd-ba5782835d34.png)
Utilizar las rutas absolutas
![image](https://user-images.githubusercontent.com/30334118/202057243-a3ef73a1-b524-4d52-9543-06abeaab8dd9.png)

Ambos componentes los probe y funcionan correctamente.

2022-11-17 19:12 UTC, milandre commented
@JorgeGarciaMdz aca falta que hagas los cambios pertinentes a lo que @SoraBeat comentó. Estaria bueno que en los otros PRs que tienes, cambies las extensiones a los archivos que falten (cambiar el .js por .jsx) y hacer las rutas de Title como rutas absolutas.
Ejem
`import Title from "Components/Title/Title"`

2022-11-17 19:13 UTC, milandre requested changes
https://github.com/alkemyTech/React-SXXI-T4/pull/28#issuecomment-1319084812

2022-11-28 09:57 UTC, milandre approved these changes

2022-11-29 19:57 UTC, merged