Feature/ong4 35/formulario edicion creacion de miembros
alkemyTech/React-SXXI-T4 pull request #3
Opened 2022-10-29 17:48 UTC by SoraBeat

En esta rama se requeria un formulario con los campos: name, image, description y links de redes sociales. Estos estan validados con yup. El manejo de la descripcion esta realizada con CKEditor 5.  Al estar todos los campos validados y apretar en enviar se muestran todos los campos ingresados por consola.
**VER EN EL CODIGO**
Hay que envolver el formulario con FormikProvider y el componente CKEditor con Field ya que no contiene el atributo "name" para la validacion del mismo.
![image](https://user-images.githubusercontent.com/30334118/198845835-46adf3a0-393d-45ec-ae1e-12bbf0bee0b9.png)

2022-11-02 02:24 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +import FormError from "../common/Form/FormError";
Sugerencia:
Para las importaciones de este estilo que se hacen largas (../../../../), es mejor configurar rutas absolutas. Se puede hacer mediante un jsconfig.json que se crea en el directorio base de tu proyecto (al nivel del package.json) y hay una opción donde puedes elegir tu directorio base y hacer las importaciones a partir de ahi.

Ejemplo:

jsconfig.json
{ "compilerOptions": { "baseUrl": "src" }, "include": ["src"] }

Quieres importar en un archivo un componente que está en src/components/Button.js, puedes hacerlo asi:
import Button from 'components/Button';

Más información en: https://create-react-app.dev/docs/importing-a-component/#absolute-imports

2022-11-02 02:46 UTC, milandre requested changes
@SoraBeat además de los reviews que hice, acá también faltaría incluir los cambios con respecto al componente de InputImage que te hice observación en el PR de ONG4 33 https://github.com/alkemyTech/React-SXXI-T4/pull/1#discussion_r1011044773

2022-11-02 02:46 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +
linea extra de espacio que debe borrarse

2022-11-02 02:46 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +
linea extra de espacio que debe borrarse

2022-11-02 02:46 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +		image: yup.string().required("Imagen obligatoria"),
Falta validación para que solo sean imagenes .png y ,jpg

2022-11-02 02:46 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +				<FormTitle>Crear/Editar Miembro</FormTitle>
Esto debería mostrar un Editar Miembro cuando estas en la vista de edición y un Crear Miembro cuando estás en la vista de creación

2022-11-02 02:46 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +				<FormSubmitButton>Enviar</FormSubmitButton>
Dejar un poco más de espacio entre el componente FormError y el botón de FormSubmitButton. 
Se ve así actualmente:
![image](https://user-images.githubusercontent.com/5572252/199382152-8288afdb-a67e-4c28-b26e-d21d1c1477a7.png)

2022-11-03 16:59 UTC, milandre requested changes

2022-11-03 16:59 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +		image: yup
Acá faltaría verificar de igual forma la validación, como lo comentado en #1

2022-11-03 16:59 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +	const SUPPORTED_FORMATS = [
Acá faltaría verificar de igual forma la validación, como lo comentado en #1

2022-11-03 16:59 UTC, milandre commented on src/Components/common/Form/InputImage.jsx
> +	const fileTypes = [
Acá faltaría verificar de igual forma la validación, como lo comentado en #1

2022-11-03 17:09 UTC, SoraBeat commented on src/Components/Members/MembersForm.jsx
> +		image: yup
Cambios realizados en el commit [1e5a828] "Validacion de imagen arreglada"

2022-11-03 17:09 UTC, SoraBeat commented on src/Components/Members/MembersForm.jsx
> +	const SUPPORTED_FORMATS = [
Cambios realizados en el commit [b246e0e] "Mover declaracion de formatos soportados"

2022-11-07 23:50 UTC, milandre approved these changes
@SoraBeat aprobado y listo para hacerle merge. Hay un tema con los archivos .jpg que no me deja agregar y me salta el cartel de "Selecciona una imagen jpg o png". Estaría bueno revisar eso antes de hacerle merge

2022-11-07 23:52 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +				<FormSubmitButton>Enviar</FormSubmitButton>
no vi que esto esté con un margen. No es bloqueante pero estaría bueno agregarlo

2022-11-08 00:02 UTC, milandre requested changes

2022-11-08 00:02 UTC, milandre commented on src/Components/Members/MembersForm.jsx
> +	const SUPPORTED_FORMATS = [
Tengo un tema con los .jpg que no me los acepta. Falta revisar qué pasa con la validación de los .jpg acá y en los demás formularios que lo requieran

2022-11-08 02:30 UTC, DiegoSantelices10 commented
lauta te dejo una solución que me funciono con el tema de la validación de la imágenes. por las!

![Screenshot_13](https://user-images.githubusercontent.com/70447941/200460511-25d894b1-54bf-4867-bf1a-2052597ce1a8.png)

2022-11-08 02:31 UTC, DiegoSantelices10 approved these changes

2022-11-08 17:14 UTC, milandre approved these changes

2022-11-16 00:47 UTC, merged