Feature/ong4 34/formulario de actualizacion de datos de organizacion
alkemyTech/React-SXXI-T4 pull request #32
Opened 2022-11-16 13:11 UTC by DiegoSantelices10

Se realizaron los cambios del diseño del BackOffice sobre los formularios.
y se agrego la condición para la subida de imagen
![Screenshot_16](https://user-images.githubusercontent.com/70447941/202189231-5ee5d1f0-eddb-4425-86ad-e1ec0974de6f.png)

2022-11-17 19:42 UTC, milandre requested changes
@DiegoSantelices10 tengo entendido que @SoraBeat tenia la tarea del Sidebar, ¿Seria lo que está aca?. En este PR deberia estar solo la actualizaci'on del formulario de datos de la organizacion y en otro PR lo del sidebar. Creen un PR a parte para el Sidebar y asi corrijo ese tambien.

2022-11-17 19:42 UTC, milandre commented on src/App.js
> +// import Layout from "./Components/Layout/Layout";
Eliminar comentario

2022-11-17 19:48 UTC, DiegoSantelices10 commented on src/App.js
> +// import Layout from "./Components/Layout/Layout";
Andre mala mia me equivoque de rama aca no iria el sidebar, el menu que es la 123 te lo envie por ese PR (sin darme cuenta hice la 126 tambien que es la de lautaro)

2022-11-17 20:00 UTC, milandre commented on src/App.js
> +// import Layout from "./Components/Layout/Layout";
Dale, si puedes revertir lo del ultimo commit o sacar de la rama las cosas del menu y sidebar seria lo mejor asi se cierra este. Avisale a @SoraBeat lo del sidebar porque el andaba trabajando en eso asi que para que unifiquen los estilos y evaluen cual es el que se queda

2022-11-18 04:49 UTC, DiegoSantelices10 commented on src/App.js
> +// import Layout from "./Components/Layout/Layout";
Se elimino el header y el sidebar perteneciente a otra tarea. completando lo pedido de esta tarea

2022-11-21 21:48 UTC, milandre approved these changes

2022-11-22 19:42 UTC, merged