Feature/ong4 65/screen listado de usuarios(backoffice)
alkemyTech/React-SXXI-T4 pull request #33
Opened 2022-11-16 23:38 UTC by SoraBeat

Se realizo el listado de los clientes, los cuales, estan paginados y filtrados segun el nombre, rol y cantidad a mostrar.
El diseño es responsive, tambien se agrego debounce a las consultas y skeleton a la hora de cargar los elementos.
Funciona el borrado, editado y creado de usuarios.
![image](https://user-images.githubusercontent.com/30334118/202318182-de675610-e75a-49d4-90be-5f3a6194ff26.png)

2022-11-21 22:00 UTC, milandre requested changes

2022-11-21 22:00 UTC, milandre commented on src/Services/UsersAdmin/ApiService.js
> -			success();
¿Por qué quitar el success acá? Revisar que esten los success() y error() acordes en este archivo y que los mensajes de sweetalert no esten repetidos en otros archivos como en el UsersList

2022-11-22 20:27 UTC, SoraBeat commented on src/Services/UsersAdmin/ApiService.js
> -			success();
Hola Andree, saque esa alerta ya que afecta negativamente a la experiencia del usuario administrador, ya que al ingresar por ejemplo en /backoffice/user/edit/1 (queriendo editar por ejemplo el usuario con el id numero 1) salta un mensaje exitoso apenas ingresas la ruta aunque no es necesario que lo haga. Igualmente ahora lo charlo con los chicos a ver que dicen.

2022-11-28 10:00 UTC, milandre approved these changes

2022-11-29 22:48 UTC, merged