Feature/ong4 37/formulario de creacion/edicion de proyectos
alkemyTech/React-SXXI-T4 pull request #34
Opened 2022-11-17 00:13 UTC by YonaBordon

Formulario Creacion / Edicion de Proyectos

- Campos title, image, description y due_date
- Reutilizable para creacion y edicion
- Validaciones

Crear
![image](https://user-images.githubusercontent.com/68975079/202321662-2799b09d-8d31-4956-8198-a6b968c38e5f.png)

Editar
![image](https://user-images.githubusercontent.com/68975079/202321473-07d3c9fe-ff4e-4bca-aafc-8440435a21a3.png)

El guardado de imagen no esta funcionando en la api, me deja guardar un string corto, pero no en base64 como los demas endpoint.
[response project error.zip](https://github.com/alkemyTech/React-SXXI-T4/files/10026598/response.project.error.zip)

2022-11-21 22:42 UTC, milandre requested changes

2022-11-21 22:42 UTC, milandre commented on src/Components/Projects/ProjectsForm.jsx
> +									<FormInputText
Cambiar este input a Ckeditor para mantener consistencia con los demas formularios. Te puedes guiar con el archivo de NewsForm.jsx que lo tiene implementado

2022-11-21 22:42 UTC, milandre commented on src/Components/Slides/SlidesForm.jsx
> +import React, { useEffect, useState } from "react";
Este archivo no debe estar en este PR ya que pertenece a la corrección del otro aca #35

2022-11-24 12:41 UTC, YonaBordon commented on src/Components/Projects/ProjectsForm.jsx
> +									<FormInputText
Cambio realizado

2022-11-28 10:04 UTC, milandre approved these changes

2022-11-28 23:09 UTC, merged