Feature/ong4 123/componente header backoffice
alkemyTech/React-SXXI-T4 pull request #36
Opened 2022-11-17 16:47 UTC by DiegoSantelices10

Se realizo el componente header para el backoffice con su sidebar.

![Screenshot_26](https://user-images.githubusercontent.com/70447941/202506108-e287f1ec-61dd-424c-9750-d67c60990937.png)
![Screenshot_23](https://user-images.githubusercontent.com/70447941/202506113-20755b64-a5d3-48d0-a8ab-2e744748b1ee.png)
![Screenshot_24](https://user-images.githubusercontent.com/70447941/202506116-73aa04e0-bc06-442b-9c6d-2a2c8ea456fd.png)
![Screenshot_25](https://user-images.githubusercontent.com/70447941/202506118-5da7e90a-de4b-44ce-b9e9-07c31b821075.png)

2022-11-21 18:02 UTC, SoraBeat approved these changes

2022-11-21 23:04 UTC, milandre requested changes

2022-11-21 23:04 UTC, milandre commented on src/App.js
> +					<Route path="/backoffice" element={<Backoffice />} />
Faltaria integrar el LayoutForm al componente de Backoffice. Lo ideal seria que el LayoutForm esté para todas las rutas del backoffice y que no se repita en cada uno de los componentes. Estaría bueno que se use una sola vez para todas las rutas del backoffice, es decir, evitar duplicar y usarlo una sola vez

2022-11-21 23:04 UTC, milandre commented on src/Components/Layout/LayoutForm/LayoutForm.jsx
> +		<div className="bg-white md:bg-slate-300 lg:bg-slate-300 w-screen h-screen mx-auto flex-col justify-center items-center ">
Faltaria agregar el logo o en su defecto el nombre de la organizacion

2022-11-21 23:08 UTC, DiegoSantelices10 commented on src/App.js
> +					<Route path="/backoffice" element={<Backoffice />} />
Dale Andre, no tuve en cuenta eso. A la noche lo modifico

2022-11-22 11:08 UTC, milandre requested changes

2022-11-22 11:08 UTC, milandre commented on src/App.js
> +// import LayoutForm from "Components/Layout/LayoutForm/LayoutForm";
Borrar comentario

2022-11-22 11:08 UTC, milandre commented on src/App.js
> +						<Route path="update-category/:id" element={<CategoriesForm />} />
Hay que revisar en cada uno de estos componentes que no esté el LayoutForm. Por ejemplo, en el NewsForm, quedó el LayoutForm y sale duplicado.

2022-11-28 10:07 UTC, milandre approved these changes

2022-11-29 01:43 UTC, merged