Feature/ong4 125/footer
alkemyTech/React-SXXI-T4 pull request #37
Opened 2022-11-17 19:17 UTC by gabrielpindo

Se realizó el componente <Footer/> que muestra información de la ONG "Somos más" de forma dinámica. 

![Footer1](https://user-images.githubusercontent.com/69809704/202538414-6e1d87c2-0d2e-45ce-b0eb-b4c616a3acbf.png)
![Footer2](https://user-images.githubusercontent.com/69809704/202538368-a0d3f0df-8472-4885-852c-c36825092147.png)
![Footer3](https://user-images.githubusercontent.com/69809704/202538376-2a512af0-3992-4315-b434-1060e37f8c94.png)

2022-11-21 18:00 UTC, SoraBeat approved these changes
Muy buen trabajo!! en lo personal diria de utilizar ruta absoluta aqui. Tambien como buena practica utilizar la etiqueta footer en vez de div como contenedor principal
![image](https://user-images.githubusercontent.com/30334118/203127037-f4a4b773-87bc-4705-b0a3-6a201ed2e9b3.png)

2022-11-21 23:44 UTC, milandre requested changes
Te dejo unos comentarios y @SoraBeat tambien

2022-11-21 23:44 UTC, milandre commented on src/Services/Organization/ApiService.js
> -		.then(res => console.log(res))
No borrar

2022-11-21 23:44 UTC, milandre commented on src/Components/Layout/components/Footer.jsx
> +						{(dataOrg.cellphone !== null) && "Celular: " + dataOrg.cellphone}
Acá pudieses usar el !! (not-not) (`!!dataOrg.cellphone`)

Más info: https://love2dev.com/blog/javascript-not-operator/

2022-11-21 23:44 UTC, milandre commented on src/Components/Layout/components/Footer.jsx
> +						{(dataOrg.address !== null) && "Dirección: " + dataOrg.address}
Acá pudieses usar el !! (not-not) (`!!dataOrg.address`)

Más info: https://love2dev.com/blog/javascript-not-operator/

2022-11-25 14:25 UTC, gabrielpindo commented
Cambios realizados.

2022-11-28 10:08 UTC, milandre approved these changes

2022-11-30 00:05 UTC, merged