Feature/ong4 126/componente side bar backoffice
alkemyTech/React-SXXI-T4 pull request #39
Opened 2022-11-18 05:25 UTC by DiegoSantelices10

Se realizo el componente Sidebar donde mostramos su funcionamiento con el Header fusionado.

![Screenshot_28](https://user-images.githubusercontent.com/70447941/202626909-e26df26f-5125-4913-999f-28f53e36050c.png)
![Screenshot_29](https://user-images.githubusercontent.com/70447941/202626914-1d62ea24-d62b-4791-94fc-dea80e7e0d71.png)

2022-11-21 17:55 UTC, SoraBeat approved these changes

2022-11-21 18:02 UTC, SoraBeat commented
Excelente trabajo!! super smooth y excelente diseño. Lo unico diria de utilizar la etiqueta aside como contenedor principal en vez de div.

2022-11-21 23:16 UTC, milandre requested changes
@DiegoSantelices10 te hice un comentario y tmb estaria bueno que revises el comentario que hizo @SoraBeat

2022-11-21 23:16 UTC, milandre commented on src/Components/SideBar/SideBar.jsx
> +							<Link to={`/backoffice/${Menu.title}`}>{Menu.title}</Link>
Acá tener en cuenta que las rutas tienen el title en lowercase asi que estaria bueno colocar esta parte `${Menu.title}` asi: `${Menu.title.toLowerCase()}`

2022-11-22 03:37 UTC, DiegoSantelices10 commented on src/Components/SideBar/SideBar.jsx
> +							<Link to={`/backoffice/${Menu.title}`}>{Menu.title}</Link>
Cambios realizados!

2022-11-22 11:11 UTC, milandre approved these changes

2022-11-22 20:17 UTC, merged