Feature/ong4 49/crear componente detalle de novedad
alkemyTech/React-SXXI-T4 pull request #4
Opened 2022-10-30 00:39 UTC by SoraBeat

En esta rama se realizo un componente el cual se renderiza al acceder a Novedades/:id el cual se le pasara un objeto con los parametros: titulo, imagen y contenido. Esto con el fin de renderizarlos por pantalla.
Los estilos estan dados por tailwind y el diseño es responsive:
**Desktop**
![image](https://user-images.githubusercontent.com/30334118/198857524-087e4de5-4846-49f2-9349-f8d01fefe246.png)
**Mobile**
![image](https://user-images.githubusercontent.com/30334118/198857592-39aac42c-09cf-4130-93ec-b03e02f86635.png)

2022-11-02 04:01 UTC, milandre requested changes

2022-11-02 04:01 UTC, milandre commented on src/Components/News/Details/NewsDetails.jsx
> +			<h1 className="text-4xl font-bold text-center pt-7">Novedades</h1>
este título hay que cambiarlo por la información que pasas por details.name (eso hace referencia al titulo de cada una de las novedades). Esto debe estar renderizado con el componente de <Title />, es decir, cuando se apruebe y se le haga merge a este PR [features/ONG4-48/ComponenteTitulo](https://github.com/alkemyTech/React-SXXI-T4/pull/9), tienes q usar ese componente acá

2022-11-02 04:01 UTC, milandre commented on src/App.js
> +	const newsDetail = {
para considerar este PR completo, el newsDetail tienes que borrarlo.

2022-11-03 17:02 UTC, milandre commented on src/Components/News/Details/NewsDetails.jsx
> +			<h1 className="text-4xl font-bold text-center pt-7">{details.name}</h1>
Acá coloco recordatorio que esto le falta agregar el componente de <Title /> cuando esté listo

2022-11-08 00:07 UTC, milandre approved these changes

2022-11-08 02:17 UTC, DiegoSantelices10 approved these changes

2022-11-14 00:47 UTC, merged