Feature/ong4 63/screen listado categorias
alkemyTech/React-SXXI-T4 pull request #40
Opened 2022-11-18 06:14 UTC by DiegoSantelices10

Se realizo en el screen para visualizar todas las categorías y tener la posibilidad de crear, editar y eliminar la misma.

![Screenshot_31](https://user-images.githubusercontent.com/70447941/202633649-a379c197-2722-4872-b1c7-759f2e35ae96.png)

2022-11-21 17:47 UTC, SoraBeat approved these changes
Esta funcional y cumple con los requisitos dados. Solo sacaria el filtro de "usuario"(el drop down list) si no es necesario. Tambien tener en cuenta los console log de prueba

2022-11-21 23:51 UTC, milandre requested changes
Dejo comentarios y sugiero leer tambien lo que dice @SoraBeat

2022-11-21 23:51 UTC, milandre commented on src/Components/Categories/index.jsx
> +				<TableDropDownList
Sacar este filtro que no corresponde a las Categorias

2022-11-21 23:51 UTC, milandre commented on src/Components/Categories/index.jsx
> +												<FaRegEdit size={30} className=" text-yellow-500" />
Aca hay un icono y en el PR #33 es un boton. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones

2022-11-21 23:51 UTC, milandre commented on src/Components/Categories/index.jsx
> +												<FaRegTrashAlt size={30} className="text-red-600" />
Aca hay un icono y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/33 es un boton. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones

2022-11-23 03:11 UTC, DiegoSantelices10 commented on src/Components/Categories/index.jsx
> +												<FaRegEdit size={30} className=" text-yellow-500" />
Vamos a dejar los iconos!

2022-11-23 03:11 UTC, DiegoSantelices10 commented on src/Components/Categories/index.jsx
> +												<FaRegTrashAlt size={30} className="text-red-600" />
Vamos a dejar los iconos!

2022-11-28 10:10 UTC, milandre approved these changes

2022-11-29 02:25 UTC, merged