Features/ong4 61/screen listado novedades
alkemyTech/React-SXXI-T4 pull request #43
Opened 2022-11-21 21:40 UTC by JorgeGarciaMdz

Se crea componente lista de novedades utilizando los componentes 'Table' definidos en common, estos componentes son definidos en las cardas 65 y 67 por lo cual no estan en dev. Tambien se crea el Servicio para las request a la api

2022-11-22 11:17 UTC, milandre requested changes

2022-11-22 11:17 UTC, milandre commented on src/Components/News/News.js
> +											<Link
Aca hay un botón y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/40 es un icono. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones/iconos

2022-11-22 11:17 UTC, milandre commented on src/Components/News/News.js
> +											<button
Aca hay un botón y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/40 es un icono. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones/iconos

2022-11-24 01:33 UTC, JorgeGarciaMdz commented on src/Components/News/News.js
> +											<Link
se cambia por icon

2022-11-24 01:33 UTC, JorgeGarciaMdz commented on src/Components/News/News.js
> +											<button
se cambia por icon

2022-11-29 11:24 UTC, milandre approved these changes

2022-11-29 19:51 UTC, merged