Feature/ong4 66/screen listado miembros ong
alkemyTech/React-SXXI-T4 pull request #44
Opened 2022-11-22 03:03 UTC by JorgeGarciaMdz

se crea componente para mostrar una lista de miembros, utilizando los componentes 'Table' que se utilizan en la card 65, por tal motivo no es incluido en este PR, dado que no esta en la rama 'dev'

2022-11-22 11:18 UTC, milandre requested changes

2022-11-22 11:18 UTC, milandre commented on src/Components/Members/Members.js
> +											<Link
Aca hay un botón y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/40 es un icono. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones/iconos

2022-11-22 11:18 UTC, milandre commented on src/Components/Members/Members.js
> +											<button
Aca hay un botón y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/40 es un icono. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones/iconos

2022-11-24 01:34 UTC, JorgeGarciaMdz commented on src/Components/Members/Members.js
> +											<Link
se cambia por icon

2022-11-24 01:34 UTC, JorgeGarciaMdz commented on src/Components/Members/Members.js
> +											<button
se cambia por icon

2022-11-29 11:26 UTC, milandre approved these changes

2022-11-29 19:19 UTC, merged