Feature/ong4 62/screen listado de actividades
alkemyTech/React-SXXI-T4 pull request #45
Opened 2022-11-22 11:16 UTC by YonaBordon

Listado de Actividades

- Mostrar el listado de actividades de la ONG
- Campos name, image, creado,
- Acciones para eliminar y editar
- Boton para crear nueva

![image](https://user-images.githubusercontent.com/68975079/203300096-6f0f87ab-de78-4877-a12f-5ba8369afd61.png)

2022-11-22 11:20 UTC, milandre requested changes

2022-11-22 11:20 UTC, milandre commented on src/Components/Activities/ActivitiesList.jsx
> +												<FaRegEdit size={30} className="text-yellow-500" />
Acá hay un icono y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/33 es un botón. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones/iconos

2022-11-22 11:20 UTC, milandre commented on src/Components/Activities/ActivitiesList.jsx
> +												<FaRegTrashAlt size={30} className="text-red-600" />
Acá hay un icono y en el PR https://github.com/alkemyTech/React-SXXI-T4/pull/33 es un botón. Sugiero ponerse de acuerdo en cual va a ser el estilo final para cada una de las tablas con respecto a estos botones/iconos

2022-11-24 12:49 UTC, YonaBordon commented on src/Components/Activities/ActivitiesList.jsx
> +												<FaRegEdit size={30} className="text-yellow-500" />
Se acordo que se van a utilizar los iconos

2022-11-24 12:49 UTC, YonaBordon commented on src/Components/Activities/ActivitiesList.jsx
> +												<FaRegTrashAlt size={30} className="text-red-600" />
Se acordo que se van a utilizar los iconos

2022-11-29 11:28 UTC, milandre approved these changes

2022-12-01 21:48 UTC, merged