Feature/ong4 25/formulario registro parcial
alkemyTech/React-SXXI-T4 pull request #5
Opened 2022-10-30 16:34 UTC by DiegoSantelices10

Se realizo el formulario de registro de usuarios para diferentes dispositivos, con sus respectivas validaciones requeridas.

![Screenshot_2](https://user-images.githubusercontent.com/70447941/198889675-962f8576-ab17-486d-bd8c-cc23493be028.png)
![Screenshot_3](https://user-images.githubusercontent.com/70447941/198889681-ee2198a0-856f-4210-a7cf-b3a9b36d4478.png)

2022-10-31 16:15 UTC, SoraBeat approved these changes
Ta joya 
![OkGIF](https://user-images.githubusercontent.com/30334118/199056434-accbd2cc-b277-46d5-bb5a-8d47d2669efa.gif)

2022-11-02 23:49 UTC, milandre commented on src/App.js
> +					{/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Esto lo coloqué en otro PR, lo coloco acá para que no se olvide de quitar los comentarios.

2022-11-03 00:07 UTC, milandre requested changes

2022-11-03 00:07 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +	console.log("hola");
Quitar console.log

2022-11-03 00:07 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +							email: yup.string().email().required(message),
Falta añadir mensaje de error en español para cuando el email no es válido y así mantener la consistencia de poner todos los mensajes de error en español

2022-11-03 00:07 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +									/^.*(?=.{6,})((?=.*[!@#$%^&*()\-_=+{};:,<.>]){1})(?=.*\d)((?=.*[a-z]){1}).*$/,
Esto puede ser también una constante como hiciste en la línea 11 (`const message = "Esta campo es obligatorio";`)

2022-11-03 00:07 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +									"La contraseña debe tener al menos una letra, un numero y simbolo, mas 6 caracteres"
Esto puede ser también una constante como hiciste en la línea 11 (`const message = "Esta campo es obligatorio";`)

2022-11-03 00:07 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +									"Las contraseñas deben coincidir"
Esto puede ser también una constante como hiciste en la línea 11 (`const message = "Esta campo es obligatorio";`)

2022-11-03 17:38 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +					<button className="text-red-600 font-medium">
Recordatorio:
Añadir <Link /> cuando este listo la ruta y vista del login para redirigir

2022-11-03 17:49 UTC, milandre requested changes
Sugiero que se reunan @gabrielpindo y @DiegoSantelices10 para hablar de consistencias de mensajes (que los mensajes de error sean los mismos para ambas vistas), consistencias de estilos y que ya agreguen la redirección al login y al registro en las partes 'Ya tienes cuenta?' y Registrar

2022-11-04 17:25 UTC, DiegoSantelices10 commented on src/App.js
> +					{/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Resuelto!

2022-11-04 17:25 UTC, DiegoSantelices10 commented on src/Components/Auth/RegisterForm.js
> +	console.log("hola");
Resuelto!

2022-11-04 17:25 UTC, DiegoSantelices10 commented on src/Components/Auth/RegisterForm.js
> +							email: yup.string().email().required(message),
Resuelto

2022-11-04 17:26 UTC, DiegoSantelices10 commented on src/Components/Auth/RegisterForm.js
> +									/^.*(?=.{6,})((?=.*[!@#$%^&*()\-_=+{};:,<.>]){1})(?=.*\d)((?=.*[a-z]){1}).*$/,
resuelto!

2022-11-04 17:26 UTC, DiegoSantelices10 commented on src/Components/Auth/RegisterForm.js
> +									"La contraseña debe tener al menos una letra, un numero y simbolo, mas 6 caracteres"
resuelto!

2022-11-04 17:27 UTC, DiegoSantelices10 commented on src/Components/Auth/RegisterForm.js
> +									"Las contraseñas deben coincidir"
resuelto!

2022-11-04 17:27 UTC, DiegoSantelices10 commented on src/Components/Auth/RegisterForm.js
> +					<button className="text-red-600 font-medium">
Resuelto!

2022-11-04 17:28 UTC, DiegoSantelices10 commented
Ahi realizamos los distintos cambios requeridos en ambas partes!

2022-11-08 00:30 UTC, milandre approved these changes
@DiegoSantelices10 haces los cambios que te dejo como comentarios y ya estaría listo para hacerle merge

2022-11-08 00:30 UTC, milandre commented on src/App.js
> +
Eliminar linea extra

2022-11-08 00:30 UTC, milandre commented on src/Components/Auth/RegisterForm.js
> +							text: `${userLogin}`,
Esto renderiza un objeto asi que quitarlo o añadir algo más informativo. Se ve con [object Object]:
![image](https://user-images.githubusercontent.com/5572252/200444388-238047c8-346b-4cf1-a0df-00f2eec32bc5.png)

2022-11-08 02:12 UTC, merged