Origin/feature/ong4 26/formulario login
alkemyTech/React-SXXI-T4 pull request #6
Opened 2022-10-31 14:34 UTC by gabrielpindo

Creación del formulario de Login de usuarios. Utilización de Formik y Yup. 
![image-20221031-050629](https://user-images.githubusercontent.com/69809704/199033130-8b63d2be-1c6c-45d2-94b2-eaf80823b20a.png)
![image-20221031-050616](https://user-images.githubusercontent.com/69809704/199033141-40bd749c-5282-4df7-83b9-d5c96be8b35b.png)
![Uploading image-20221031-050731.png…]()

2022-11-03 17:19 UTC, SoraBeat commented
Hay que borrar este comentario xd, por lo demas esta joya 👌
![image](https://user-images.githubusercontent.com/30334118/199790001-e09fe656-dae7-4f9f-9017-741ec033c875.png)

2022-11-03 17:48 UTC, milandre requested changes
@gabrielpindo reviews hechos en base a lo que verifiqué también en el PR #5 . Sugiero que se reunan @gabrielpindo y @DiegoSantelices10 para hablar de consistencias de mensajes (que los mensajes de error sean los mismos para ambas vistas), consistencias de estilos y que ya agreguen la redirección al login y al registro en las partes **'Ya tienes cuenta?'** y **Registrar**

2022-11-03 17:48 UTC, milandre commented on src/App.js
>            {/* <Route path="/" exact component={} />           Esta ruta debe ser para el Home */}
Quitar comentario

2022-11-03 17:48 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +									/^.*(?=.{6,})((?=.*[!@#$%^&*()\-_=+{};:,<.>]){1})(?=.*\d)((?=.*[a-z]){1}).*$/,
Esto puede ser también una constante como hiciste en la línea 6 (`const message = "Por favor, completa los campos";`)

2022-11-03 17:48 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +									"La contraseña debe tener una longitud mínima de 6 caraceteres, y contener al menos un número, una letra y un símbolo"
Esto puede ser también una constante como hiciste en la línea 6 (const message = "Por favor, completa los campos";)

2022-11-03 17:48 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +					<a
Recordatorio:
Añadir cuando este listo la ruta y vista del register para redirigir

2022-11-08 00:43 UTC, milandre requested changes

2022-11-08 00:43 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +					<Link className="text-red-600 font-medium" to="/register-user">
Falta añadir la ruta de /register-user al App.js

2022-11-08 00:43 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +							position: "top-end",
Sale en la esquina superior derecha. Revisar #5 src/Components/Auth/RegisterForm.js para ver el estilo del alert del registro porque no son consistentes.

2022-11-08 00:43 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +							text: `${loginData.email}`,
Ver el texto de esto porque sale undefined
![image](https://user-images.githubusercontent.com/5572252/200446053-cc1ded28-a116-4735-ba1f-f160a49722ca.png)

2022-11-16 21:32 UTC, milandre requested changes

2022-11-16 21:32 UTC, milandre commented on src/Components/Auth/LoginForm.js
> +									<img src="images/logo-somosmas.png" />
El logo no se encuentra en images, está en Assets/images. Revisar esto y sugiero que se queden con una sola carpeta para las imagenes de logos, etc., es decir, seleccionar una de estas: Assets o images

2022-11-25 17:28 UTC, gabrielpindo commented
@milandre, se realizaron todos los cambios. Falta aprobación.

2022-11-28 09:45 UTC, milandre approved these changes

2022-11-29 23:09 UTC, merged