Fix/modificacion diseño card
alkemyTech/React-SXXI-T4 pull request #69
Opened 2022-12-01 15:21 UTC by SoraBeat

Se realizo un cambios de estilos al componente card ya que no se adaptaba a los distintos estilos que requeria la pagina. Ahora acepta un parametro type que puede ser "version1" o "version2".

2022-12-01 15:36 UTC, DiegoSantelices10 approved these changes

2022-12-05 01:17 UTC, milandre requested changes

2022-12-05 01:17 UTC, milandre commented on src/Components/Card/Card.jsx
> +const Card = ({type, facebook,linkedin,image,description,title}) => {
Atar el diseño de card a un tipo (type) genera acoplamiento entre este y los diferentes tipos que se vayan agregando luego. ¿Qué pasa si tengo muchos? Tendría que hacer un if por cada uno de estos y luego el mantenimiento es engorroso. Sugiero entonces pasar como props los estilos y que el componente padre se encargue de pasarlo o también está la opción de pasar como `children` desde el padre lo que quieres visualizar en la card (ejemplo, cada bloque que tienes para la verison2 y version1). Considerar tambien los cambios que va a implicar esto en todas las demas vistas

2022-12-13 22:33 UTC, milandre commented
@SoraBeat deja cuando puedas una respuesta en el comentario que hice acá para ver si es necesario hacer este fix

2022-12-14 03:32 UTC, SoraBeat commented on src/Components/Card/Card.jsx
> +const Card = ({type, facebook,linkedin,image,description,title}) => {
Hola @milandre disculpa la tardanza, esta rama ya no la vamos a implementar ya que se hicieron los cambios pertinentes en la rama "ArreglosDev" tendria que borrar esta rama y su respectivo PR?

2022-12-14 21:21 UTC, milandre commented on src/Components/Card/Card.jsx
> +const Card = ({type, facebook,linkedin,image,description,title}) => {
Voy a cerrar este PR entonces. La rama la puedes borrar

2022-12-14 21:22 UTC, closed without merging