Feature/ong4 38/formulario de suscripcion newsletter
alkemyTech/React-SXXI-T4 pull request #7
Opened 2022-10-31 17:51 UTC by SoraBeat

En esta rama se realizo un componente llamado FormNewsletter el cual solo contiene un campo(email) y un boton submit. El siguiente se debera mostrar si en el local storage no aparece que se haya subscripto. En cambio, si se suscribio, no se debera mostrar este componente.
LOCALSTORAGE VACIO // SE MUESTRA
![image](https://user-images.githubusercontent.com/30334118/199075161-d3bd9d64-492c-4e34-9571-2cdec92096ec.png)
SE VALIDA QUE SE INGRESO ALGO // FORMIK Y YUP
![image](https://user-images.githubusercontent.com/30334118/199075303-ae5044dc-a07e-4a17-9bbd-7b9a295173f8.png)
UNA VEZ SUSCRITO NO SE MOSTRARA EL COMPONENTE
![image](https://user-images.githubusercontent.com/30334118/199075400-69f64ab9-3860-4cf7-b762-218909b0173f.png)

2022-11-03 20:21 UTC, milandre requested changes

2022-11-03 20:21 UTC, milandre commented on src/Components/Layout/components/FormNewsletter.jsx
> +				<form className="flex flex-col w-64 gap-2 my-2" onSubmit={handleSubmit}>
Mejorar la posición donde se muestra. Centrar y agregarle espacios entre botones/input de formulario. Que quede algo así pero mejorado. 
![image](https://user-images.githubusercontent.com/5572252/199825919-afbf7c49-cafe-4b27-ac47-b53ac5a7e728.png)

Para esto, hablar con el equipo y decidir estilo

2022-11-08 00:58 UTC, milandre approved these changes

2022-11-08 02:26 UTC, DiegoSantelices10 approved these changes

2022-11-14 00:52 UTC, merged