Feature/ong4 106/creacion store autenticacion auth reducer
alkemyTech/React-SXXI-T4 pull request #74
Opened 2022-12-06 04:08 UTC by DiegoSantelices10

Se creo el store para la autenticación del usuario

2022-12-06 19:11 UTC, milandre requested changes

2022-12-06 19:11 UTC, milandre commented on src/utils/messages/formMessagesValidation.js
> +	password6: "La contraseña debe contener al enos 6 caracteres, una letra, un numero y un simbolo $%#",
Falta una 'm' en 'al enos 8 caracteres'

2022-12-06 19:11 UTC, milandre commented on src/utils/messages/formMessagesValidation.js
> +	password8: "La contraseña debe contener al enos 8 caracteres, una letra, un numero y un simbolo $%#",
Falta una 'm' en 'al enos 8 caracteres'

2022-12-06 19:11 UTC, milandre commented on src/Components/Categories/CategoriesForm.jsx
> +						console.log("entro");
Eliminar console.log

2022-12-06 19:11 UTC, milandre commented on src/Components/SideBar/MenuSideBar.jsx
> +	const { isLoggedIn, token } = useSelector(state => state.user);
El manejo del isLoggedIn deberia estar es en LayoutForm ya que es el layout base para el backoffice

2022-12-06 19:11 UTC, milandre commented on src/Components/SideBar/MenuSideBar.jsx
> +	if (!isLoggedIn) {
Esta redirección deberia estar en LayoutForm, ya que es el layout base para el backoffice

2022-12-06 19:11 UTC, milandre commented on src/Services/Category/ApiService.js
> +			console.log(res);
Borrar console.log

2022-12-06 19:11 UTC, milandre commented on src/Services/Category/categoriesServices.js
> +	console.log(res);
Borrar console.log

2022-12-06 19:11 UTC, milandre commented on src/store/Slices/authSlice.js
> +		builder.addCase(signIn.pending, (state, action) => {
¿Es necesario agregar este caso para cuando está el signIn pending? Ya en el initialState tienes isLoggedIn en false y eso debe cambiar cuando se haya loggeado correctamente

2022-12-06 19:11 UTC, milandre commented on src/store/Slices/authSlice.js
> +		builder.addCase(signUp.pending, (state, action) => {
Acá no tendría sentido agregar este caso porque cuando te registras y todo marcha bien, te debe redirigir a la vista de login. Por lo tanto, el isLoggedIn debe permanecer en false

2022-12-06 19:11 UTC, milandre commented on src/store/Slices/authSlice.js
> +		builder.addCase(signUp.fulfilled, (state, payload) => {
Acá no tendría sentido agregar este caso porque ya tienes el initialState con isLoggedIn en false

2022-12-06 19:11 UTC, milandre commented on src/store/Slices/authSlice.js
> +		builder.addCase(signUp.rejected, (state, action) => {
Acá no tendría sentido agregar este caso porque ya tienes el initialState con isLoggedIn en false

2022-12-06 19:11 UTC, milandre commented on src/store/app/store.js
> +		message: messageSlice,
No me queda claro la utilidad de tener message. ¿Qué quisieras lograr acá con este agregado?

2022-12-06 19:49 UTC, DiegoSantelices10 commented
Listo andre ahi estuve resolviendo las cosas que me pediste!!

2022-12-12 17:43 UTC, milandre requested changes

2022-12-12 17:43 UTC, milandre commented on src/Components/Layout/components/Navbar.jsx
> +							src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAAAXNSR0IArs4c6QAAAlxJREFUSEuFloFtGzEMRR8n8AhNN3BH8ARBJ3Buoo5Qj5ARPIJHyAjOBCwoUTqK0rkBHB1wEj/5+T91gv8JAijqK321J0HLvvq/7
Acá hay que cambiar el src para que referencie a una de las imagenes q están en sus Assets, como los casos anteriores que están en este archivo

2022-12-12 17:43 UTC, milandre commented on src/Components/Layout/components/Navbar.jsx
> +							src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAAAXNSR0IArs4c6QAAAdRJREFUSEuNVomRAyEMkzu5TrKlpJNsOrvOuAMbkM23mckkAS+WbMlEwC8RICW3BAFAS+Enxa538hl5t7zqF04jEKScZZaM1sZnb
Acá hay que cambiar el src para que referencie a una de las imagenes q están en sus Assets, como los casos anteriores que están en este archivo

2022-12-13 02:12 UTC, milandre approved these changes

2022-12-13 03:15 UTC, merged