Feature/ong4 36/formulario de contacto
alkemyTech/React-SXXI-T4 pull request #8
Opened 2022-11-01 01:42 UTC by DiegoSantelices10

Se realizó el formulario de contacto para los usuarios, utilizamos Formik y yup para sus respectivas validaciones.

![Screenshot_4](https://user-images.githubusercontent.com/70447941/199140245-09fbe81c-3708-44b2-9b64-a0cb59ef8d37.png)

2022-11-03 17:23 UTC, SoraBeat commented
Hay que borrar este comentario
![image](https://user-images.githubusercontent.com/30334118/199791181-4338e2ba-1746-493c-84f1-43765593949b.png)
Demasiados espacios en blanco entre clases
![image](https://user-images.githubusercontent.com/30334118/199791282-324a9838-4503-43a7-bb9b-90c47ea007c6.png)
Por lo demas pienso que esta bien ^^

2022-11-08 03:35 UTC, milandre requested changes

2022-11-08 03:35 UTC, milandre commented on src/Components/Contact/ContactForm.js
> +							text: `${contactMessage.name}`,
Revisar `${contactMessage.name}` que sale undefined
![image](https://user-images.githubusercontent.com/5572252/200468737-fa37af2f-fb13-4e6d-b492-331494953946.png)

2022-11-08 03:35 UTC, milandre commented on src/Components/Contact/ContactForm.js
> +							phone: yup
¿Cómo asegurar que es un número de teléfono? Al ser string, ya cuando cumple el min y max de caracteres, me lo valida como correcto. En la historia de usuario dice que debe ser un número. 

Ejemplo de lo que sucede con el campo de phone:
![image](https://user-images.githubusercontent.com/5572252/200469023-95cd0de8-dd61-4e1e-aa22-20f5117df201.png)

2022-11-09 04:19 UTC, DiegoSantelices10 commented
Andre ahí realice los cambios requeridos!

2022-11-13 17:02 UTC, milandre approved these changes

2022-11-14 19:24 UTC, merged