Feature/ONG4-130/PáginaDeError404
alkemyTech/React-SXXI-T4 pull request #82
Opened 2022-12-14 02:02 UTC by gabrielpindo

Se realizó la página de error 404.

![image](https://user-images.githubusercontent.com/69809704/207486675-bd7d6acc-a340-4809-b92b-3a7b926190a7.png)
![image](https://user-images.githubusercontent.com/69809704/207486716-9ce99b5c-01e7-4d2f-b1ee-7d332548901f.png)

2022-12-14 21:28 UTC, milandre requested changes

2022-12-14 21:28 UTC, milandre commented on src/App.js
> +import HomeForm from "Components/Home/HomeForm";
Creo que este ya no lo usan y están usando el componente de Home, correcto?

2022-12-15 14:01 UTC, gabrielpindo commented on src/App.js
> +import HomeForm from "Components/Home/HomeForm";
En realidad ambos se utillizan, el componente HomeForm es el que va en el backoffice.

2022-12-16 17:41 UTC, milandre approved these changes

2022-12-16 17:41 UTC, milandre commented on src/App.js
> +import HomeForm from "Components/Home/HomeForm";
Ok, no lo había visto en las rutas

2022-12-17 15:07 UTC, merged