Feature/ong4 154/testing formulario datos ong
alkemyTech/React-SXXI-T4 pull request #86
Opened 2022-12-16 03:03 UTC by SoraBeat

En esta rama se realizo testing al componente formulario de datos de la organizacion

2022-12-16 17:39 UTC, milandre requested changes

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +	const inputName = await screen.findByPlaceholderText("Ingresa el nombre de la Organizacion");
Acá como un tip de mejora estaría bueno que coloques primero todos los const y luego hagas los expect.
Acá un articulo de interes:
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.click(submitButton);
Esta es una acción que el usuario realiza. Estaría bueno cambiarlo por userEvent.click
Más informción acá: https://testing-library.com/docs/user-event/intro

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputName, { target: { value: "ONG somos mas" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputLongDescription, { target: { value: "Descripcion larga" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputShortDescription, { target: { value: "Descripcion corta" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.click(buttonOKImage);
Acá estaría bueno hacer userEvent.click

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputFacebook, { target: { value: "asd" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputLinkedin, { target: { value: "asd" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputInstagram, { target: { value: "asd" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputTwitter, { target: { value: "asd" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputFacebook, { target: { value: "https://www.facebook.com" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputLinkedin, { target: { value: "https://www.linkedin.com" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputInstagram, { target: { value: "https://www.instagram.com" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.change(inputTwitter, { target: { value: "https://www.twitter.com" } });
Acá estaría bueno hacer userEvent.type

2022-12-16 17:39 UTC, milandre commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.click(submitButton2);
Esta es una acción que el usuario realiza. Estaría bueno cambiarlo por userEvent.click
Más informción acá: https://testing-library.com/docs/user-event/intro

2022-12-17 00:20 UTC, SoraBeat commented on src/Components/Organization/OrganizationForm.test.js
> +		fireEvent.click(submitButton2);
@milandre  Muchas gracias Andre por el feedback, ahi realice las correcciones!!

2022-12-17 18:49 UTC, milandre approved these changes

2022-12-17 19:36 UTC, merged