features/ONG4-48/ComponenteTítulo
alkemyTech/React-SXXI-T4 pull request #9
Opened 2022-11-01 12:55 UTC by gabrielpindo

Creación del componente "Title", recibe como parámetro una cadena de texto para mostrarla como título, y una dirección de imagen, para utilizarla como fondo.

2022-11-02 03:40 UTC, milandre requested changes

2022-11-02 03:40 UTC, milandre commented on src/App.js
> +import Test from './Components/Title/Test'
Para considerar este PR completo, todas las cosas referidas a test se deben retirar. Basta con que en la descripción esté un ejemplo visual (como ya lo colocaste)

2022-11-02 03:40 UTC, milandre commented on src/App.js
> +          <Route path="/test" element={<Test/>}/>
Quitar esta ruta de prueba

2022-11-02 03:40 UTC, milandre commented on src/Components/Title/Test.jsx
> +import React from 'react'
Quitar este archivo

2022-11-05 17:55 UTC, SoraBeat commented
Buenas, estuve usando este componente y falta un requisito que es: en caso de no recibir ninguna imagen debera mostrar una por defecto.
![image](https://user-images.githubusercontent.com/30334118/200134246-f0bda80c-63a5-4b89-b072-348fa5d318aa.png)
Tambien revisar los estilos que se le aplican a la imagen: Que no se repita el fondo, que la imagen este centrada en el medio, que tenga un tamaño adecuado, etc.

2022-11-08 03:38 UTC, milandre commented
> Buenas, estuve usando este componente y falta un requisito que es: en caso de no recibir ninguna imagen debera mostrar una por defecto. ![image](https://user-images.githubusercontent.com/30334118/200134246-f0bda80c-63a5-4b89-b072-348fa5d318aa.png) Tambien revisar los estilos que se le aplican a la imagen: Que no se repita el fondo, que la imagen este centrada en el medio, que tenga un tamaño adecuado, etc.

@gabrielpindo faltaría revisar estas cosas también

2022-11-08 17:18 UTC, milandre approved these changes

2022-11-25 17:27 UTC, merged